services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html/
    ports:
      - "8002:80"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: notes_app
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: escript-vue-phpmyadmin
    platform: linux/arm64
    restart: always
    ports:
      - "8003:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql_data:
